name: GREAT_Lab_Web
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - flask
  - flask-mail
  - werkzeug
  - matplotlib
  - ephem
  - sqlite 
  - google-auth-oauthlib
  - google-auth
  - google-auth-httplib2
  - google-api-python-client
  - astropy
  - slack-sdk
  - pip
  - pip:
      - obsplanning
      - ploty
